# Generated by Django 5.1 on 2024-08-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="key",
            new_name="category",
        ),
    ]
